---
title: "How a Data Scientist Prepares for the Crossfit Open"
author: "Brian Davis"
date: "February 21, 2017"
output: html_document
---

```{r xtable, results='asis'}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(scales)
library(xtable)

## Load and Clean Data ---------------------------------------------------------

# read the data in (generated by propel_affiliate_scrape.R)
athletes <- readRDS(file = "../data/Propel/propel_athlete_profiles_2017.rds")

# Fix a couple people who entered their height as inches
ht_tbl <- athletes %>% 
  filter(height < 12) %>% 
  select(athlete_name, affiliate, division, height)

set_names(ht_tbl, c("Name", "Affiliate", "Division", "Height")) 
print(xtable(ht_tbl, digits=0), type="html",html.table.attributes = "style='width:600px'", include.rownames=FALSE)
```

## AGE

```{r}
athletes <- athletes %>% 
  mutate(height = if_else(height < 12, 12*height, height),
         age_group =  factor(x = gsub(" (Men|Women|Boys|Girls)", '', division),
                             levels = c("Teenage (14-15)", "Teenage (16-17)",
                                        "Individual", "Masters (35-39)",
                                        "Masters (40-44)", "Masters (45-49)",
                                        "Masters (50-54)", "Masters (55-59)",
                                        "Masters (60+)"),
                             labels = c("14-15", "16-17", "18-34", "35-39",
                                        "40-44", "45-49", "50-54", "55-59",
                                        "60+")))

ggplot(athletes, mapping = aes(x=age_group, fill = gender)) +
  geom_bar(aes(y=..count../sum(..count..)), position="dodge") +
  scale_y_continuous(labels=percent) +
  labs(fill="Gender",x='Age Group',y="% of Athletes") +
  theme_bw(base_size=18) +
  theme(legend.position = c(.9, .9))
```

