##------------------------------------------------------------------------------
## Summarize Crossfit Propel profile data from athletes in 2017 Open
##
## Notes:
##  * uses data scraped by propel_affiliate_scrape.R
##  * used to create this post:
##    http://davisbrian.github.io/
##
##------------------------------------------------------------------------------
library(tidyverse)
library(lubridate)
library(ggplot2)
library(scales)
library(knitr)
library(printr)
# library(xtable)

## Load and Clean Data ---------------------------------------------------------

# read the data in (generated by propel_affiliate_scrape.R)
athletes <- readRDS(file = "./data/Propel/propel_athlete_profiles_2017.rds")
athletes <- readRDS(file = "~/Projects/crossfitr/data/Propel/propel_athlete_profiles_2017.rds")

# functions for later
height_as_text <- function(ht) {
  paste0(floor(ht/12L), "' ", ht%%12L, "\"")
}

ht_tbl <- athletes %>% 
  filter(height < 12) %>% 
  select(athlete_name, division, height) %>%
  mutate(height = height_as_text(height))

# Add in "genderless" Division
athletes <- athletes %>% 
  mutate(height = if_else(height < 12, 12*height, height),
         age_group =  factor(x = gsub(" (Men|Women|Boys|Girls)", '', division),
                             levels = c("Teenage (14-15)", "Teenage (16-17)",
                                        "Individual", "Masters (35-39)",
                                        "Masters (40-44)", "Masters (45-49)",
                                        "Masters (50-54)", "Masters (55-59)",
                                        "Masters (60+)"),
                             labels = c("14-15", "16-17", "18-34", "35-39",
                                        "40-44", "45-49", "50-54", "55-59",
                                        "60+")))


## Summarize Age - Distribution  (Division) ------------------------------------
div_plot <- ggplot(athletes, mapping = aes(x=age_group, fill = gender)) +
  geom_bar(position="dodge") +
  labs(fill="Gender",x='Age Group',y="Number of Athletes") +
  theme_bw(base_size=18) +
  theme(legend.position = c(.9, .9))

ggsave(width=10, height=6,
       plot=div_plot,
       filename="Propel_division_plot.png")

# y axis as percentage
div_plot2 <- ggplot(athletes, mapping = aes(x=age_group, fill = gender)) +
  geom_bar(aes(y=..count../sum(..count..)), position="dodge") +
  scale_y_continuous(labels=percent) +
  labs(fill="Gender",x='Age Group',y="% of Athletes") +
  theme_bw(base_size=18) +
  theme(legend.position = c(.9, .9))


ggsave(width=10, height=6,
       plot=div_plot2,
       filename="Propel_division_plot2.png")

## Summarize Height Distribution -----------------------------------------------
variable <- "height"
binwidth <- 1
limits   <- c(57, 76)
breaks   <- seq(57, 81, by = 3)
labels   <- c("4\'9\"","5\'","5\'3\"","5\'6\"","5\'9\"","6\'","6\'3\"","6\'6\"","6\'9\"")
xlab     <- "Height (feet/in)"

ht_plot <- ggplot(athletes, mapping = aes(x=height, fill = gender)) +
  geom_histogram(aes(y=..density..),binwidth=binwidth, position="dodge") +
  geom_density(alpha=.4,adjust=3, color=NA) +
  scale_y_continuous(labels=percent) +
  scale_x_continuous(limits = limits,
                     breaks = breaks,
                     labels = labels) +
  labs(fill="Gender",x=xlab,y="% of Athletes") +
  theme_bw(base_size=18) +
  theme(legend.position = c(.9, .9))

ggsave(width=10, height=6,
       plot=ht_plot,
       filename="Propel_height_plot.png")



## Counts of Benchmark Stats
fix_benchmark <- function(x) {
  x <- gsub("_", ' ', x)
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
        sep="", collapse=" ")
}

bstats <- athletes %>%
  gather("metric", "value", 10:21) %>% 
  group_by(metric) %>%
  summarise(cnt = sum(!is.na(value)),
            miss = sum(is.na(value))) %>%
  mutate(metric = sapply(metric, fix_benchmark)) %>%
  arrange(desc(cnt))

knitr::kable(bstats, 
             col.names=c("Benchmark Stat", "Count", "Missing"), align = c('l', 'c', 'c'))


bstats$metric <- gsub("_", ' ', bstats$metric)

bstats %>% View()

# Calculate the missing rates for each stat
